--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 12.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: tb_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_order_item (
    price double precision,
    quantity integer,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: tb_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_payment (
    moment timestamp without time zone,
    order_id bigint NOT NULL
);


--
-- Name: tb_product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: td_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.td_category (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: td_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.td_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.td_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: td_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.td_order (
    id bigint NOT NULL,
    moment timestamp without time zone,
    order_status integer,
    client_id bigint
);


--
-- Name: td_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.td_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.td_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: td_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.td_product (
    id bigint NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision
);


--
-- Name: td_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.td_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.td_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_order_item tb_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT tb_order_item_pkey PRIMARY KEY (order_id, product_id);


--
-- Name: tb_payment tb_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT tb_payment_pkey PRIMARY KEY (order_id);


--
-- Name: tb_product_category tb_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT tb_product_category_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: td_category td_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.td_category
    ADD CONSTRAINT td_category_pkey PRIMARY KEY (id);


--
-- Name: td_order td_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.td_order
    ADD CONSTRAINT td_order_pkey PRIMARY KEY (id);


--
-- Name: td_product td_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.td_product
    ADD CONSTRAINT td_product_pkey PRIMARY KEY (id);


--
-- Name: td_order fk9pwosakrwr255lncxwudxfy2k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.td_order
    ADD CONSTRAINT fk9pwosakrwr255lncxwudxfy2k FOREIGN KEY (client_id) REFERENCES public.tb_user(id);


--
-- Name: tb_payment fkb3iogyilmoqxb0a2s8w5g98g0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT fkb3iogyilmoqxb0a2s8w5g98g0 FOREIGN KEY (order_id) REFERENCES public.td_order(id);


--
-- Name: tb_order_item fkg7xkjqiefq6smip3t4mwnh5tj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fkg7xkjqiefq6smip3t4mwnh5tj FOREIGN KEY (order_id) REFERENCES public.td_order(id);


--
-- Name: tb_product_category fkhlkyivmvt50cjg3kugd46udxr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkhlkyivmvt50cjg3kugd46udxr FOREIGN KEY (product_id) REFERENCES public.td_product(id);


--
-- Name: tb_product_category fkptavd6waa56akbx7wrcxvkqhp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkptavd6waa56akbx7wrcxvkqhp FOREIGN KEY (category_id) REFERENCES public.td_category(id);


--
-- Name: tb_order_item fksgd1i92epn7m075ia6hbwnfme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fksgd1i92epn7m075ia6hbwnfme FOREIGN KEY (product_id) REFERENCES public.td_product(id);


--
-- PostgreSQL database dump complete
--

